# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmFjODkwZWMwNzk2ZGM4YTQ0OWJmMzQ5NjFiMzMwMzM1MDEyZjQ1MTRiMTc0NjhkZTY5YTAyNDA0MTk3ZDgzOGExMmJhOTJiZjlhNDQ1ZmNiZTgzODVjOTFkMmI5NjA5ZjhmMTFmYTRkZmI5ZjU5MDc0MDFhODlkN2M4YjljYzU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
